// Generated by CoffeeScript 1.12.6
var fs, get, mime;

fs = require("fs");

mime = require("mime");

get = function(res, req) {
  res.setHeader('Content-type', mime.lookup("pages/index.html"));
  return fs.readFileSync("pages/index.html");
};

module.exports = {
  get: get,
  address: "",
  mimetype: "html"
};
