// Generated by CoffeeScript 1.12.6
(function() {
  var connect, mainLoop, nicked, parse, sendText;

  nicked = false;

  connect = function(again) {
    var nick;
    if (again == null) {
      again = false;
    }
    if (again) {
      nick = Window.prompt("Already used! Use another nickname:", "default_user1");
    } else {
      nick = Window.prompt("Set your nickname:", "default_user");
    }
    return $.get(window.location.href.substring(0, window.location.href.lastIndexOf('/') + 1) + "/connect", {
      nick: nick
    }, function(data, status, req) {
      if (!data["continue"]) {
        return connect(true);
      }
    }, "json");
  };

  sendText = function() {
    var data, inputBox;
    if (!nicked) {
      false;
    }
    inputBox = document.getElementByID("textArea");
    data = inputBox.value;
    $.get(window.location.href.substring(0, window.location.href.lastIndexOf('/') + 1) + "/sendchat", {
      text: data
    }, null, "json");
    return true;
  };

  parse = function(logs) {
    var d, i, len, results;
    results = [];
    for (i = 0, len = logs.length; i < len; i++) {
      d = logs[i];
      results.push(document.getElementByID("logs").innerHTML += "\n<" + logs.nickname + "> " + logs.data);
    }
    return results;
  };

  mainLoop = function() {
    return $.get(window.location.href.substring(0, window.location.href.lastIndexOf('/') + 1) + "/getchat", {}, function(data, status, req) {
      parse(data.logs);
      return Window.setTimeout(data.next, mainLoop);
    }, "json");
  };

  window.onunload = function() {
    return $.get(window.location.href.substring(0, window.location.href.lastIndexOf('/') + 1) + "/disconnect", {}, null, "json");
  };

  connect();

  nicked = true;

  mainLoop();

}).call(this);
