// Generated by CoffeeScript 1.12.6
var connect, disconnect, mainLoop, nick, nicked, parse, sendText, validateSendText;

nicked = false;

nick = null;

connect = function(again) {
  if (again == null) {
    again = false;
  }
  if (again) {
    nick = window.prompt("Already used! Use another nickname:", "default_user1").replace("&", "&amp;").replace("<", "&lt;").replace("\"", "&quot;").replace("'", "&apos;").slice(0, 50);
  } else {
    nick = window.prompt("Set your nickname:", "default_user").replace("&", "&amp;").replace("<", "&lt;").replace("\"", "&quot;").replace("'", "&apos;").slice(0, 50);
  }
  return $.ajax("../connect", {
    type: "POST",
    data: JSON.stringify({
      nick: nick
    }),
    success: function(data, status, req) {
      if (!data["continue"]) {
        return connect(true);
      }
    },
    contentType: 'application/json'
  });
};

sendText = function() {
  var data, inputBox;
  if (!nicked) {
    return false;
  }
  inputBox = document.getElementById("textArea");
  data = inputBox.value;
  if (data === "") {
    return false;
  }
  inputBox.value = "";
  $.ajax("../sendchat", {
    type: "POST",
    data: JSON.stringify({
      text: data,
      nick: nick
    }),
    success: null,
    contentType: 'application/json'
  });
  return true;
};

validateSendText = function(event) {
  if (event.keyCode === 13) {
    return sendText();
  }
};

parse = function(logs) {
  var d, i, len, results;
  results = [];
  for (i = 0, len = logs.length; i < len; i++) {
    d = logs[i];
    if ((d.text != null) && d.text !== "") {
      if (d.text.indexOf(nick) !== -1 && d.highlight && d.nick !== nick) {
        new Audio("../highlight.wav").play();
        d.text = d.text.replace(new RegExp(nick, "g"), '<span class="highlight"><span id="nick" /></span>').replace('<span id="nick" />', nick);
      }
      console.log(d.text);
      results.push(document.getElementById("logs").innerHTML += "</br>" + d.text);
    } else {
      results.push(void 0);
    }
  }
  return results;
};

mainLoop = function() {
  var scroll;
  scroll = document.getElementById("logs").scrollTop === (document.getElementById("logs").scrollHeight - document.getElementById("logs").offsetHeight);
  return $.ajax("../getchat", {
    type: "POST",
    data: JSON.stringify({
      nick: nick
    }),
    success: function(data, status, req) {
      if (data["continue"] != null) {
        if (data.logs != null) {
          parse(data.logs);
          window.setTimeout(mainLoop, data.next * 1000);
        } else {
          window.setTimeout(mainLoop, 5000);
        }
      } else {
        disconnect();
      }
      if (scroll) {
        return document.getElementById("logs").scrollTop = document.getElementById("logs").scrollHeight - document.getElementById("logs").offsetHeight;
      }
    },
    contentType: 'application/json'
  });
};

disconnect = function() {
  document.getElementById("inputs").parentNode.removeChild(document.getElementById("inputs"));
  $.ajax("../disconnect", {
    type: "POST",
    data: JSON.stringify({
      nick: nick
    }),
    success: null,
    contentType: 'application/json'
  });
  return document.getElementById("logs").innerHTML += "</br>--- Disconnected.";
};

window.onload = function() {
  connect();
  nicked = true;
  return window.setTimeout(mainLoop, 1000);
};
