// Generated by CoffeeScript 1.12.6
var post, sbserv;

sbserv = require("../server.js").sbserv;

post = function(req, res) {
  if (sbserv.newUser(req.get("X-FORWARDED-FOR"), req.body.nick)) {
    console.log("JSON request body: " + JSON.stringify(req.body));
    return {
      "continue": true
    };
  } else {
    return {
      "continue": false
    };
  }
};

module.exports = {
  post: post,
  address: "connect",
  mimetype: "application/json"
};
