// Generated by CoffeeScript 1.12.6
var post, sbserv;

sbserv = require("../server.js").sbserv;

post = function(res, req) {
  if (sbserv.newUser(req.ip, req.body.nick)) {
    return res.send("{continue: true}");
  } else {
    return res.send("{continue: false}");
  }
};

module.exports = {
  post: post,
  address: "connect",
  mimetype: "application/json"
};
