// Generated by CoffeeScript 1.12.6
(function() {
  var post, sbserv,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  sbserv = require("../server.js").sbserv;

  post = function(res, req) {
    var ref;
    if (ref = req.ip, indexOf.call(sbserv.ips, ref) >= 0) {
      if (sbserv.newUser(req.ip, req.body.nick)) {
        return "{continue: true}";
      } else {
        return "{continue: false}";
      }
    }
  };

  module.exports = {
    post: post,
    address: "connect"
  };

}).call(this);
