// Generated by CoffeeScript 1.12.6
(function() {
  var data, sbserv,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  sbserv = require("../server.coffee").sbserv;

  data = function(res, req) {
    var ref;
    if (ref = req.ip, indexOf.call(sbserv.ips, ref) >= 0) {
      sbserv.disconnect(req.ip, sbserv.ips[req.ip]);
      return "{}";
    }
  };

  module.exports = {
    data: data,
    address: "disconnect"
  };

}).call(this);
