// Generated by CoffeeScript 1.12.6
var post, sbserv;

sbserv = require("../server.js").sbserv;

post = function(req, res) {
  var _, a, ref;
  ref = sbserv.ips;
  for (a in ref) {
    _ = ref[a];
    if (req.get("X-FORWARDED-FOR") === a) {
      sbserv.disconnect(req.get("X-FORWARDED-FOR"), sbserv.ips[req.get("X-FORWARDED-FOR")]);
    }
  }
  return {};
};

module.exports = {
  post: post,
  address: "disconnect",
  mimetype: "application/json"
};
