// Generated by CoffeeScript 1.12.6
var post, sbserv;

sbserv = require("../server.js").sbserv;

post = function(req, res) {
  var _, a, r, ref;
  ref = sbserv.ips;
  for (a in ref) {
    _ = ref[a];
    if (req.get("X-FORWARDED-FOR") === a) {
      r = sbserv.serveAjax(req.get("X-FORWARDED-FOR"), "getchat", req.body);
      r["continue"] = true;
      return r;
    }
  }
  return {
    "continue": false
  };
};

module.exports = {
  post: post,
  address: "getchat",
  mimetype: "application/json"
};
