// Generated by CoffeeScript 1.12.6
var post, sbserv;

sbserv = require("../server.js").sbserv;

post = function(req, res) {
  var _, a, ref;
  console.log(JSON.stringify(req.body));
  ref = sbserv.ips;
  for (a in ref) {
    _ = ref[a];
    if (req.remoteIP() === a) {
      return sbserv.serveAjax(req.remoteIP(), "kick", req.body);
    }
  }
  return {};
};

module.exports = {
  post: post,
  address: "kick",
  mimetype: "application/json"
};
