// Generated by CoffeeScript 1.12.6
(function() {
  var app, dynasite;

  dynasite = require("./request.coffee");

  app = dynasite.DynasiteApp();

  app.webFolder("pages/");

  app.done();

}).call(this);
