// Generated by CoffeeScript 1.12.6
(function() {
  var DynasiteApp, express;

  express = require('express');

  DynasiteApp = (function() {
    var constructor, done, webFolder;

    function DynasiteApp() {}

    constructor = function() {
      this.app = express();
      return this.modules = [];
    };

    webFolder = function(f) {
      return fs.readdir(fxs(function(err, files) {
        var fn, i, len, module, results;
        if (err) {
          throw err;
        }
        results = [];
        for (i = 0, len = fxs.length; i < len; i++) {
          fn = fxs[i];
          if (f.endsWith(".node") || f.endsWith(".node.js")) {
            module = require(fn);
            this.app.get(fn.address, function(req, res) {
              return res.send(fn.data(req, res));
            });
            results.push(this.modules.push(module));
          } else {
            results.push(this.app.get(path.relative(f, fn), function(req, res) {
              return fs.readFile(fn, function(err, data) {
                if (err) {
                  throw err;
                }
                return res.send(data);
              });
            }));
          }
        }
        return results;
      }));
    };

    done = function(port) {
      if (port == null) {
        port = 3000;
      }
      return this.app.listen(port, function() {
        var i, len, m, ref, results;
        console.log("Listening on port " + port + ".");
        ref = this.modules;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          m = ref[i];
          if (m.init != null) {
            results.push(m.init(port));
          } else {
            results.push(void 0);
          }
        }
        return results;
      });
    };

    return DynasiteApp;

  })();

  module.exports = {
    DynasiteApp: DynasiteApp
  };

}).call(this);
