// Generated by CoffeeScript 1.12.6
(function() {
  var sbserv,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  sbserv = {};

  sbserv.ips = {};

  sbserv.pendingData = {};

  sbserv.users = [];

  sbserv.newUser = function(ip, nick) {
    if (indexOf.call(sbserv.users, nick) >= 0) {
      false;
    }
    sbserv.users.push(nick);
    sbserv.pendingData[nick] = [];
    sbserv.ips[ip] = nick;
    return true;
  };

  sbserv.disconnect = function(ip, nick) {
    var k, ref, v;
    if (sbserv.ips[ip] !== nick) {
      false;
    }
    sbserv.users.remove(nick);
    sbserv.pendingData[nick] = void 0;
    ref = sbserv.ips;
    for (k in ref) {
      v = ref[k];
      if (v === nick) {
        sbserv.ips[k] = void 0;
      }
    }
    return true;
  };

  sbserv.relay = function(nick, text) {
    return sbserv.pendingData[nick].push({
      nick: nick,
      text: text
    });
  };

  sbserv.serveAjax = function(ip, addr, data) {
    var logs;
    if (addr === "sendchat") {
      sbserv.relay(sbserv.ips[ip], data.text);
      return {};
    } else if (addr === "getchat") {
      logs = sbserv.pendingData[sbsev.ips[ip]];
      sbserv.pendingData[sbsev.ips[ip]] = void 0;
      return {
        logs: logs,
        next: 0.8
      };
    }
  };

  module.exports = {
    sbserv: sbserv
  };

}).call(this);
